import {byId} from '../data/cards.js';
import {spriteStyle} from '../data/art.js';
import {gameIcon} from './icons.js';
import {cardBadges,cardName,cardDetails,controlIcon} from './card-details.js';
export function manual(C){
 const example=id=>{const c=byId(id);return `<section class="manual-example"><div class="manual-card card-art" style="${spriteStyle(c.name)}">${cardBadges(c)}<i class="example-energy">${c.cost}${gameIcon('ENERGIA')}</i>${cardName(c.name)}</div><div><h3>${c.name}</h3>${cardDetails(c)}</div></section>`};
 return `<div class="rules illustrated-manual"><h2>${controlIcon('book')} Regole di BRISCOLA MAGICATA</h2><p>Prepara le difese, gestisci l’energia e conquista la cittadella avversaria.</p>
 <h3>Obiettivo</h3><p>${gameIcon('INTEGRITA')} Porta il nucleo avversario da ${C.RULES.CORE_INTEGRITY} a 0 integrità. Oppure mantieni almeno ${C.RULES.DOMINION_THRESHOLD} Dominio per ${C.RULES.DOMINION_TURNS_TO_WIN} inizi consecutivi dei tuoi turni. I droni distrutti fanno perdere il loro Dominio.</p>
 <h3>Prima mano: prepara la tua strategia</h3><p>Ricevi ${C.RULES.STARTING_HAND} carte. Puoi disporre fino a ${C.RULES.MOVES_PER_TURN} carte utilizzabili della mano iniziale, spendendo energia. In questa fase niente attacchi dei droni né ${gameIcon('LASER')} danni immediati: virus e radiazioni si installano ma colpiranno nei turni successivi. Premi INIZIA anche se non hai carte disponibili: la partita aspetta entrambi.</p>
 <h3>Leggere una carta</h3><p>In alto a sinistra: icona del tipo e valore di attacco o protezione. Sotto: ${gameIcon('INTEGRITA')} integrità del drone oppure numero di cariche radioattive. In alto a destra: costo ${gameIcon('ENERGIA')}, verde se puoi pagarlo, rosso se non hai energia sufficiente. Tocca una carta per vedere valori e regole, poi GIOCA.</p>
 ${example('drone-1')}${example('radiazione-3')}${example('scudo-1')}
 <h3>Turni, pesca ed energia</h3><p>La mano iniziale non viene cancellata. All’inizio di ogni tuo turno di battaglia peschi ${C.RULES.DRAW_PER_TURN} carta e ricarichi l’energia al tuo massimo. La mano può contenere ${C.RULES.MAX_HAND} carte: le pescate in eccesso vanno negli scarti. Il mazzo è mescolato alla creazione; non si riempie automaticamente la mano fino a cinque.</p><p>Parti da ${C.RULES.START_MAX_ENERGY} energia massima. Ai turni globali 3, 6, 9… aumenta di 1 il massimo del giocatore attivo, fino a ${C.RULES.ABSOLUTE_MAX_ENERGY}. Dopo le due preparazioni la battaglia riparte dal turno 3.</p><p>Hai ${C.RULES.MOVES_PER_TURN} mosse. Giocare una carta o attaccare con un drone consuma una mossa. Il turno termina automaticamente quando non restano azioni valide; puoi anticiparlo con FINE TURNO.</p>
 <h3>Come vengono assorbiti i danni</h3><p>${gameIcon('SCUDO')} Scudi → ${gameIcon('DRONE')} droni → ${gameIcon('INTEGRITA')} nucleo. Il danno residuo passa alla difesa successiva; un drone a zero integrità è distrutto.</p><p>${gameIcon('LASER')} Laser: danno immediato. Intercettazione riduce di 2 il primo laser da almeno 4 danni. ${gameIcon('VIRUS')} Virus: si risolve e scompare all’inizio del turno del bersaglio. ${gameIcon('RADIAZIONE')} Radiazione: una carica e un danno per inizio turno. Se il mazzo è esaurito, ogni pesca mancata provoca danni crescenti; questi superano i droni, ma possono essere assorbiti dagli scudi.</p>
 <h3>Briscola e Magicate</h3><p>Controlla la Briscola nella barra sopra l’arena. I bonus applicati ai valori sono mostrati nel dettaglio delle carte. ${gameIcon('MAGICATA')} Le Magicate possono far pescare e recuperare integrità, scambiare radiazioni, ridurre le mosse avversarie o cambiare Briscola: leggi l’effetto della carta.</p>
 <h3>Arena e comandi</h3><p>＋/− regolano lo zoom. La freccia porta la camera dietro la tua cittadella; il quadrato ripristina la vista. I pulsanti inferiori ai lati aprono i pannelli grandi dei giocatori. Tocca un drone schierato per ordinarne l’attacco.</p><p>${controlIcon('explosion')} RAPPORTO DANNI mostra i danni ricevuti con data, ora, turno, carta e ripartizione fra difese e nucleo. Il Registro del menu conserva anche le altre azioni. Nel menu Mazzo puoi consultare le tue carte per categoria, in ordine casuale e senza svelare l’ordine di pesca.</p>
 <h3>Singleplayer e multiplayer</h3><p>Contro la CPU, ogni carta giocata viene mostrata prima dell’azione successiva. Online puoi giocare mentre l’altro è collegato oppure tornare più tardi: non c’è un limite di tempo per il turno. Le carte non giocate dell’avversario restano coperte.</p><p>Le animazioni mostrano in sequenza le azioni già confermate. Non cambiano l’ordine della partita: attendi la fine della sequenza prima di impartire un comando. Il rapporto danni resta consultabile anche dopo vittoria o sconfitta.</p></div>`;
}
