import assert from 'node:assert/strict';
import * as THREE from '../vendor/three.module.min.js';
import {TableRenderer,radiationBatch} from '../src/render/table.js';
import {newGame,act,endTurn} from '../src/game/engine.js';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
const config={window:{}};vm.runInNewContext((await readFile(new URL('../index.html',import.meta.url),'utf8')).match(/<script>([\s\S]*?)<\/script>/)[1],config);const C=config.window.CONFIG;
let state=newGame(C,51,undefined,{prepare:false});
state.players[0].hand=['laser-1','scudo-1'];state.players[0].energy=10;
state=act(state,C,{type:'play',cardId:'laser-1',target:1});
assert.equal(state.visualEvents[0].kind,'laser');assert.equal(state.visualEvents[0].target,1);
state.players[1].viruses=[{uid:'v-test',name:'Virus',amount:1}];state.players[1].radiation=2;state.players[1].radiationUnits=['r-1-1-0','r-1-1-1'];
state=endTurn(state,C);
assert(state.visualEvents.some(e=>e.kind==='virus'&&e.sourceUid==='v-test'));
assert(state.visualEvents.some(e=>e.kind==='radiazione'&&e.sourceUid==='r-1-1-0'));
const r=Object.create(TableRenderer.prototype);Object.assign(r,{effects:new THREE.Group(),units:new THREE.Group(),models:new Map(),variants:new Map(),unitMeshes:new Map(),effectQueue:[],lasers:[],impacts:[],camera:new THREE.OrthographicCamera(-8,8,4.5,-4.5,.1,50),target:new THREE.Vector3()});
r.collectDamage({...state,visualEvents:[],nextVisualId:0});r.collectDamage(state);const count=r.effectQueue.length;assert(count>=3);r.collectDamage(state);assert.equal(r.effectQueue.length,count,'polling must not replay events');
r.advanceEffects(0);assert.equal(r.lasers.length,1);r.update(state);assert.equal(r.lasers.length,1,'scene rebuild preserves live damage');
for(let time=600;time<6000;time+=600)r.advanceEffects(time);
assert.equal(r.effectQueue.length,0);assert.equal(r.effects.children.length,0);
r.collectDamage({...state,gameId:'another-game'});assert.equal(r.effectQueue.length,0,'initial load skips old events');
assert.equal(radiationBatch('r-12-2-0'),radiationBatch('r-12-2-5'));
r.behindView(0);assert(r.camera.position.x<0);assert(r.target.x>0);r.zoomBy(1);assert(r.camera.zoom>1);r.behindView(1);assert(r.camera.position.x>0);assert(r.target.x<0);r.resetView();assert.equal(r.cameraMode,'standard');assert.equal(r.camera.position.z,16.5);
console.log('effects: authoritative damage, polling deduplication, rebuild continuity, cleanup, radiation batches and both camera sides: ok');
