import{newGame,act,endTurn,autoPlay}from'./game/engine.js';import{byId,CARD_POOL,preset}from'./data/cards.js';import{LocalGameAdapter}from'./storage/adapter.js';import{TableRenderer}from'./render/table.js';
document.title='BRISCOLA MAGICATA';document.querySelector('.brand').innerHTML='BRISCOLA <span>MAGICATA</span> <small>ASYNCHRONOUS CARD CONFLICT</small>';
// Layout mobile: la mano scorre col pollice e Fine Turno resta sempre raggiungibile.
document.head.insertAdjacentHTML('beforeend',`<style>
@media(max-width:600px){
 body{font-size:15px;padding-bottom:82px;overflow-x:hidden}header{position:sticky;top:0;z-index:4;padding:8px 10px;gap:6px;background:#070b1df5}.brand{font-size:17px;line-height:1.1}.brand small{font-size:6px}#turnBanner{order:3;margin:0;width:100%;font-size:10px}nav{margin-left:auto;display:grid;grid-template-columns:repeat(4,1fr);gap:3px}nav button,.import{font-size:8px;padding:7px 4px;text-align:center}main{display:flex;flex-direction:column;gap:7px;padding:8px}.player-area{padding:9px}.player-area .core{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin:7px 0;padding:8px}.player-area .core>b,.player-area .stats{grid-column:1/-1}.units{grid-template-columns:repeat(3,1fr);gap:4px}.units strong{margin-top:3px}.units span,.drone{font-size:10px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}#arena{order:-1;min-height:240px}#threeCanvas{height:240px}#centerHud{inset:7px;align-items:flex-start}.briscola{max-width:70%;padding:6px;font-size:10px}.briscola b{font-size:11px}.briscola small{font-size:7px}.moves{padding:6px;font-size:10px}#logPanel{margin:0 8px;height:116px;padding:8px;font-size:12px}#logPanel h2{font-size:10px}#log p{margin:2px 0}footer{padding:0 8px}#hand{min-height:170px;gap:7px;padding:8px 1px 4px;scroll-snap-type:x mandatory;-webkit-overflow-scrolling:touch}.card{flex-basis:132px;min-height:154px;padding:8px;scroll-snap-align:start}.card:hover,.card.selected{transform:translateY(-4px)}.card b{font-size:14px}.card small{font-size:11px}#actions{position:fixed;z-index:5;bottom:0;left:0;right:0;min-height:72px;padding:9px 10px calc(9px + env(safe-area-inset-bottom));background:#080d22f5;border-top:1px solid #345589;gap:6px}#selected{display:none}#endTurn,#aiBtn{min-height:44px;flex:1;font-size:12px}.modal{padding:10px}.modal article{width:100%;padding:20px 14px;font-size:14px}.pool{grid-template-columns:1fr;font-size:12px}
}
@media(min-width:601px) and (max-width:900px){#actions{position:sticky;bottom:0;background:#080d22;padding:10px;z-index:2}.card{flex-basis:150px}}
</style>`);
document.head.insertAdjacentHTML('beforeend',`<style>
#logPanel{display:none}.brand span{color:#ff354c}
@media(max-width:600px){#logButton,#menuButton{display:block;padding:7px 10px;font-size:20px;line-height:1}#logButton{margin-left:auto}#menuButton{margin-left:2px}#hand{padding-top:2px}.card{max-height:142px}}
@media(min-width:601px){#logButton{display:none}}
</style>`);
const C=window.CONFIG,A=new LocalGameAdapter();let s=A.load()||newGame(C),selected=null;const $=q=>document.querySelector(q),esc=x=>String(x).replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]));const R=new TableRenderer($('#threeCanvas'),C);
// La camera e la tavola restano nella stessa vista standard tra un turno e l'altro.
const standardTableUpdate=R.update.bind(R);R.update=(state)=>{standardTableUpdate(state);let n=0;state.players.forEach((p,i)=>{let side=i?2.7:-2.7;let core=R.group.children[n++];if(core){core.position.x=side;core.position.z=0}p.drones.forEach((d,k)=>{let piece=R.group.children[n++];if(piece){piece.position.x=side+(i?-0.8:0.8);piece.position.z=-.9+k*.7}});p.shields.forEach((d,k)=>{let piece=R.group.children[n++];if(piece){piece.position.x=side+(i?-.7:.7);piece.position.z=.9-k*.55}})});R.group.rotation.y=0};
document.head.insertAdjacentHTML('beforeend',`<style>@media(max-width:600px){#mobileStatus{height:${30/textScale}svh;padding:3px 8px;gap:4px}.mobile-player{height:100%;max-height:none}.mobile-name{font-size:12px}.mobile-meter{font-size:11px}.mobile-list,.mobile-list span,.mobile-list button{font-size:11px}.mobile-list b{font-size:9px}#hand{align-items:flex-start!important;padding:2px 0!important}.card{height:66%;min-height:0!important;max-height:66%!important}.card b{font-size:17px}.card small{font-size:12px}.mobile-list button{min-height:36px;display:flex;align-items:center}.mobile-list .info-row{min-height:36px;display:flex;align-items:center;width:100%}#centerHud .briscola{padding:7px;max-width:70%}#centerHud .briscola b{font-size:11px;white-space:nowrap}#turnBanner{white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-size:11px}}</style>`);
// Scala reale dell'interfaccia: include anche testi con dimensioni CSS espresse in pixel.
const textScale=Math.max(.75,Math.min(1.5,C.UI_TEXT_SCALE||1));document.body.style.zoom=textScale;
// Con lo zoom, le altezze si compensano: le carte restano sempre dentro al display.
document.head.insertAdjacentHTML('beforeend',`<style>
@media(max-width:600px){
 /* Sul telefono si scala solo il testo: nessun elemento può uscire dal display. */
 body{zoom:${textScale}!important;overflow:hidden}#app{height:${100/textScale}svh!important}#arena,#threeCanvas{height:${23/textScale}svh!important}#logPanel{display:none!important}footer{min-height:0}#hand{overflow-y:hidden}
 .mobile-player{max-height:${18/textScale}svh;overflow-y:auto;overscroll-behavior:contain}.modal{top:${72/textScale}px!important;bottom:${120/textScale}px!important;padding:max(12px,env(safe-area-inset-top)) max(12px,env(safe-area-inset-right)) max(12px,env(safe-area-inset-bottom)) max(12px,env(safe-area-inset-left))}.modal article{max-height:calc(${100/textScale}svh - ${216/textScale}px - env(safe-area-inset-top) - env(safe-area-inset-bottom));padding-bottom:26px}.modal article .close{position:sticky;display:block;float:none;margin-left:auto;top:0;z-index:3}.modal-close-bottom{display:block;width:100%;margin-top:18px}
}
</style>`);
document.querySelector('header').insertAdjacentHTML('beforeend','<button id="logButton" aria-label="Apri il Registro di Battaglia">▣</button><button id="menuButton" aria-label="Apri il menu">☰</button>');document.querySelector('#arena').insertAdjacentHTML('afterend','<section id="mobileStatus" aria-label="Stato dei giocatori"></section>');
document.head.insertAdjacentHTML('beforeend',`<style>
.brand span{color:#ff354c}@media(max-width:600px){body{padding-bottom:0;overflow:hidden}#app{height:100dvh;display:flex;flex-direction:column}header{flex:0 0 auto}header nav{display:none;position:absolute;right:8px;top:48px;width:185px;padding:8px;background:#0b1230;border:1px solid #4266a8;grid-template-columns:1fr 1fr;z-index:9}header.menu-open nav{display:grid}#menuButton{display:block;margin-left:auto;padding:7px 10px;font-size:20px;line-height:1}main{display:block;flex:0 0 auto;padding:5px 8px}.player-area{display:none}#arena{height:23dvh;min-height:150px}#threeCanvas{height:23dvh;min-height:150px}#mobileStatus{display:grid;grid-template-columns:1fr 24px 1fr;gap:5px;padding:5px 8px;flex:0 0 auto}.vs{align-self:center;text-align:center;font:bold 11px monospace;color:#f5ca56}.mobile-player{min-width:0;padding:7px;background:#0a1028;border:1px solid #294879}.mobile-player.you{border-color:#37e9ff}.mobile-player.enemy{border-color:#ff354c}.mobile-name{font:bold 10px monospace;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.you .mobile-name{color:#37e9ff}.enemy .mobile-name{color:#ff354c}.mobile-meter{margin-top:4px;font-size:9px}.mobile-meter label{display:flex;justify-content:space-between}.mobile-meter i{display:block;height:4px;background:#172643}.mobile-meter em{display:block;height:100%}.mobile-list{display:grid;gap:2px;margin-top:5px;font-size:9px}.mobile-list b{color:#9ebbe9;font-size:8px}.mobile-list span,.mobile-list button{font-size:9px;padding:2px;background:#142241;border:0;color:#d9e8ff;text-align:left;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}#logPanel{flex:0 0 11dvh;height:11dvh;margin:0 8px;padding:6px;overflow:auto}#summary{font-size:11px}footer{display:flex;flex-direction:column;flex:1;min-height:0;padding:0 8px}#hand{flex:1;min-height:0;height:auto;padding:6px 0;align-items:center}.card{flex-basis:118px;min-height:142px}.card small{font-size:10px}#actions{position:static;flex:0 0 auto;min-height:54px;padding:5px 0 8px;background:transparent;border:0}#endTurn,#aiBtn{min-height:42px}.briscola{max-width:72%;font-size:9px}.briscola span{display:none}.moves{font-size:9px}.modal article{max-height:90dvh}.rules h2{font-size:18px}.rules h3{color:#ffca67;margin:16px 0 4px}.rules p,.rules li{font-size:14px;line-height:1.35}}
@media(min-width:601px){#mobileStatus,#menuButton{display:none}}
</style>`);
function mobileMeter(label,v,max,color){return`<div class="mobile-meter"><label>${label}<b>${v}/${max}</b></label><i><em style="width:${Math.min(100,v/max*100)}%;background:${color}"></em></i></div>`}function mobilePlayer(p,kind){return`<div class="mobile-player ${kind}"><div class="mobile-name">${kind==='you'?'TU · ':'AVVERSARIO · '}${esc(p.name)}</div>${mobileMeter('INTEGRITÀ',p.integrity,C.RULES.CORE_INTEGRITY,C.COLORS.INTEGRITY)}${mobileMeter('ENERGIA',p.energy,p.maxEnergy,C.COLORS.ENERGY)}<div class="mobile-list"><span>◆ DOMINIO ${p.dominance}/${C.RULES.DOMINION_THRESHOLD} · ☢ ${p.radiation}</span><b>SCUDI</b>${p.shields.map(x=>`<button type="button" class="info-row" title="Scudo: ${esc(x.name)}">⬡ ${esc(x.name)} ${x.amount}</button>`).join('')||'<span>—</span>'}<b>VIRUS</b>${p.viruses.map(x=>'<button type="button" class="info-row" title="Virus latente">⌘ Anomalia</button>').join('')||'<span>—</span>'}<b>DRONE</b>${p.drones.map(x=>`<button data-attack="${x.uid}" class="${x.used?'used':''}">◈ ${esc(x.name)} ${x.attack}/${x.hp}</button>`).join('')||'<span>—</span>'}</div></div>`}
function updateMobileStatus(){let p=s.players[s.active],o=s.players[1-s.active];$('#mobileStatus').innerHTML=`${mobilePlayer(p,'you')}<div class="vs">VS</div>${mobilePlayer(o,'enemy')}`}
setTimeout(()=>{let baseRender=render;render=()=>{baseRender();updateMobileStatus();if(matchMedia('(max-width:600px)').matches){$('#turnBanner').textContent=`BRISCOLA ATTIVA · ${s.briscola.name}`;$('#centerHud .briscola').innerHTML=`<b>TURNO ${s.turnId} · ${esc(s.players[s.active].name)}</b>`}};render()},0);
$('#menuButton').onclick=()=>document.querySelector('header').classList.toggle('menu-open');
$('#logButton').onclick=()=>modal('registro',`<div class="rules"><h2>Registro di Battaglia</h2><p>Qui trovi ogni azione già risolta, utile per riprendere una partita asincrona.</p><div id="modalLog">${s.history.map(x=>`<p><b>Turno ${x.turnId}</b> — ${esc(x.text)}</p>`).join('')}</div></div>`);
// Quando la partita finisce, il pannello esito offre sempre una nuova partita immediata.
new MutationObserver(()=>{let article=document.querySelector('#modalRoot article');if(article&&/VITTORIA|SCONFITTA/.test(article.textContent)&&!article.querySelector('#restartGame'))article.insertAdjacentHTML('beforeend','<button id="restartGame" class="primary">RICOMINCIA PARTITA</button>')}).observe($('#modalRoot'),{childList:true,subtree:true});
document.addEventListener('click',e=>{if(e.target.closest('#restartGame')){s=newGame(C);selected=null;$('#modalRoot').innerHTML='';render()}},true);
new MutationObserver(()=>{let article=document.querySelector('#modalRoot article');if(article&&!article.querySelector('#closeModal'))article.insertAdjacentHTML('beforeend','<button id="closeModal" class="modal-close-bottom">CHIUDI</button>')}).observe($('#modalRoot'),{childList:true,subtree:true});
document.addEventListener('click',e=>{if(e.target.closest('#closeModal'))$('#modalRoot').innerHTML=''},true);
function richRules(){return`<div class="rules"><h2>Regole di BRISCOLA MAGICATA</h2><p><b>Scopo della partita.</b> Vinci in due modi: riduci l’<b>Integrità</b> del Nucleo avversario a zero, oppure inizia ${C.RULES.DOMINION_TURNS_TO_WIN} dei tuoi turni consecutivi con almeno ${C.RULES.DOMINION_THRESHOLD} punti <b>Dominio</b>. Non esiste un timer: la partita può proseguire per giorni.</p><h3>1. Turni, Energia e mosse</h3><p>Nel tuo turno l’Energia torna al massimo attuale e peschi una carta. Puoi eseguire fino a ${C.RULES.MOVES_PER_TURN} mosse: giocare una carta, attivare un effetto o ordinare l’attacco di un Drone. Puoi terminare anche prima con <b>Fine Turno</b>; dopo la conferma il turno non può essere modificato.</p><h3>2. Nucleo, Integrità e Scudi</h3><p>Il <b>Nucleo</b> è la Cittadella Orbitale del giocatore: parte con ${C.RULES.CORE_INTEGRITY} Integrità. Gli <b>Scudi</b> sono protezioni installate davanti al Nucleo: assorbono il danno in ordine, poi l’eventuale danno residuo colpisce il Nucleo. Alcuni Scudi hanno varianti speciali, ma tutti mostrano chiaramente la protezione rimasta.</p><h3>3. Drone</h3><p>I <b>Drone</b> sono unità meccaniche persistenti: restano sul tavolo e hanno Attacco/Integrità, ad esempio 2/3. Clicca un Drone disponibile per ordinargli un attacco al Nucleo nemico: conta come una mossa. Un Drone può attaccare una volta per turno; alcuni producono Dominio o hanno abilità difensive.</p><h3>4. Virus e Radiazione</h3><p>I <b>Virus</b> sono sabotaggi informatici installati sull’avversario. L’avversario vede un’anomalia, e il Virus si attiva automaticamente all’inizio del suo turno: nessuna risposta in tempo reale è richiesta. La <b>Radiazione</b> (☢) è un danno persistente: ogni inizio turno infligge 1 danno e diminuisce di 1, fino a sparire.</p><h3>5. Laser, Briscola e Magicate</h3><p>I <b>Laser</b> infliggono danno immediato e costano Energia. La <b>Briscola</b> è una regola globale estratta periodicamente: vale per entrambi fino alla successiva. Le <b>Magicate</b> sono carte rare e potenti, con effetti insoliti ma sempre registrati nel Registro di Battaglia.</p><h3>6. Registro, Direttive e mazzo</h3><p>Il <b>Registro di Battaglia</b> racconta azioni, danni, scudi, Briscole ed effetti risolti, così puoi riprendere una partita asincrona senza dubbi. Le <b>Direttive</b> sono reazioni automatiche impostate in precedenza. Se il mazzo finisce, ogni pesca mancata causa danno crescente al proprietario.</p></div>`}
document.addEventListener('click',e=>{let b=e.target.closest('[data-modal="rules"]');if(b){e.stopImmediatePropagation();modal('rules',richRules())}},true);
function meter(label,v,max,color){return`<div class="meter"><label>${label} <b>${v}/${max}</b></label><i><em style="width:${Math.min(100,v/max*100)}%;background:${color}"></em></i></div>`}function player(p,enemy){return`<div class="area-title">${enemy?'AVVERSARIO':'TU'} · ${p.name}</div><div class="core"><b>◉ NUCLEO</b>${meter('INTEGRITÀ',p.integrity,C.RULES.CORE_INTEGRITY,C.COLORS.INTEGRITY)}${meter('ENERGIA',p.energy,p.maxEnergy,C.COLORS.ENERGY)}<div class="stats">◆ DOMINIO <b>${p.dominance}/${C.RULES.DOMINION_THRESHOLD}</b> · ☢ ${p.radiation}</div></div><div class="units"><strong>SCUDI</strong> ${p.shields.map(x=>`<span>⬡ ${esc(x.name)} ${x.amount}</span>`).join('')||'—'}<strong>DRONE</strong>${p.drones.map(x=>`<button class="drone ${x.used?'used':''}" data-attack="${x.uid}" title="Attacca: ${x.attack} danni">◈ ${esc(x.name)} ${x.attack}/${x.hp}</button>`).join('')||'—'}<strong>VIRUS</strong>${p.viruses.map(x=>`<span>⌘ Anomalia</span>`).join('')||'—'}</div>`}
function render(){let p=s.players[s.active],o=s.players[1-s.active];$('#opponent').innerHTML=player(o,true);$('#current').innerHTML=player(p,false);$('#turnBanner').textContent=`TURNO ${s.turnId} · ${p.name}`;$('#centerHud').innerHTML=`<div class="briscola"><small>BRISCOLA ATTIVA · ROUND ${s.round}</small><b>${s.briscola.icon} ${esc(s.briscola.name)}</b><span>${esc(s.briscola.description)}</span></div><div class="moves">MOSSE <b>${s.movesUsed} / ${C.RULES.MOVES_PER_TURN+(s.temp.reducedMoves[s.active]||0)}</b></div>`;$('#summary').textContent=s.history[0]?.text||'';$('#log').innerHTML=s.history.slice(0,18).map(x=>`<p class="${x.type}"><small>T${x.turnId}</small> ${esc(x.text)}</p>`).join('');$('#hand').innerHTML=p.hand.map(id=>{let c=byId(id);return`<button class="card ${selected===id?'selected':''}" data-card="${id}" style="--c:${c.color}" title="${esc(c.description)}"><span>${c.icon} ${c.category}</span><b>${esc(c.name)}</b><i>${c.cost} ⚡</i><small>${esc(c.description)}</small></button>`}).join('');$('#selected').textContent=selected?`Carta selezionata: ${byId(selected).name}. Clicca di nuovo per giocarla contro l’avversario.`:'Seleziona una carta per leggere il tooltip e giocarla.';$('#endTurn').disabled=!!s.winner;R.update(s);A.save(s);if(s.winner!==null)modal('fine',`<h2>${s.winner===s.active?'VITTORIA':'SCONFITTA'}</h2><p>${s.players[s.winner].name} controlla il settore orbitale.</p>`)}
function doAct(a){try{s=act(s,C,a);selected=null;render()}catch(e){alert(e.message)}}document.addEventListener('click',e=>{let c=e.target.closest('[data-card]');if(c){let id=c.dataset.card;if(selected===id)doAct({type:'play',cardId:id,target:1-s.active});else{selected=id;render()}return}let d=e.target.closest('[data-attack]');if(d)doAct({type:'attack',uid:d.dataset.attack});let m=e.target.dataset.modal;if(m)showModal(m)});$('#endTurn').onclick=()=>{let remaining=C.RULES.MOVES_PER_TURN+(s.temp.reducedMoves[s.active]||0)-s.movesUsed;if(remaining>0&&!confirm(`Restano ${remaining} mosse. Confermi Fine Turno?`))return;s=endTurn(s,C);render()};$('#aiBtn').onclick=()=>{for(let i=0;i<C.RULES.MOVES_PER_TURN;i++)s=autoPlay(s,C);s=endTurn(s,C);render()};$('#saveBtn').onclick=()=>{A.save(s);alert('Salvataggio locale aggiornato.')};$('#resetBtn').onclick=()=>{if(confirm('Eliminare il salvataggio locale e iniziare una nuova partita?')){A.clear();s=newGame(C);render()}};$('#exportBtn').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([A.export(s)],{type:'application/json'}));a.download='neon-war-save.json';a.click();URL.revokeObjectURL(a.href)};$('#importInput').onchange=async e=>{try{s=A.import(await e.target.files[0].text());render()}catch(x){alert('Importazione non valida: '+x.message)}};
function modal(kind,content){$('#modalRoot').innerHTML=`<div class="modal"><article><button class="close">×</button>${content}</article></div>`;$('.close').onclick=()=>$('#modalRoot').innerHTML=''}function showModal(k){if(k==='rules')modal(k,`<h2>REGOLE</h2><p>Riduci l’Integrità avversaria a zero o mantieni ${C.RULES.DOMINION_THRESHOLD} Dominio per ${C.RULES.DOMINION_TURNS_TO_WIN} turni propri. Ogni turno hai ${C.RULES.MOVES_PER_TURN} mosse e l’Energia si ripristina. Scudi assorbono danni; Drone attaccano; Virus e Radiazione colpiscono nel turno futuro; la Briscola cambia le regole globali.</p><h3>Direttive</h3><p>Sono reazioni automatiche già impostate: non richiedono che l’avversario sia connesso.</p>`);if(k==='tutorial')modal(k,`<h2>TUTORIAL RAPIDO</h2><ol><li>Scegli una carta dalla mano; cliccala di nuovo per usarla.</li><li>Usa Drone persistenti cliccandoli.</li><li>Controlla Energia e MOSSE, poi premi Fine Turno.</li><li>Leggi il Registro al centro per ricostruire una partita asincrona.</li></ol>`);if(k==='deck')modal(k,`<h2>DECK BUILDING</h2><p>Mazzi pronti: Bastione Orbitale e Piaga Rossa (30 carte, massimo ${C.RULES.MAX_MAGIFICATE} Magicate). Il pool contiene ${CARD_POOL.length} carte; in questa versione i mazzi pronti sono bilanciati e modificabili in <code>src/data/cards.js</code>.</p><button id="bast">USA BASTIONE</button> <button id="piaga">USA PIAGA ROSSA</button><div class="pool">${CARD_POOL.map(c=>`<span>${c.icon} ${esc(c.name)} (${c.cost})</span>`).join('')}</div>`);setTimeout(()=>{let b=$('#bast'),p=$('#piaga');if(b)b.onclick=()=>{s=newGame(C);s.players[0].deck=preset('BASTIONE ORBITALE');render();$('#modalRoot').innerHTML=''};if(p)p.onclick=()=>{s=newGame(C);s.players[0].deck=preset('PIAGA ROSSA');render();$('#modalRoot').innerHTML=''}},0)}render();
