import{newGame,act,endTurn,autoPlay,legal}from'./game/engine.js';import{byId,CARD_POOL,DECK_CATEGORIES,DECK_LIMITS,DEFAULT_DECK_COUNTS}from'./data/cards.js';import{LocalGameAdapter}from'./storage/adapter.js';import{TableRenderer}from'./render/table.js';
document.title='BRISCOLA MAGICATA';document.querySelector('.brand').innerHTML='BRISCOLA <span>MAGICATA</span> <small>ASYNCHRONOUS CARD CONFLICT</small>';document.querySelector('.brand').style.visibility='visible';
// Layout mobile: la mano scorre col pollice e Fine Turno resta sempre raggiungibile.
document.head.insertAdjacentHTML('beforeend',`<style>.card-preview{min-width:min(330px,88vw);border:2px solid var(--c);padding:14px;background:linear-gradient(150deg,#162952,#0c1026)}.card-preview>span{color:var(--c);font:13px monospace}.card-preview h2{font-size:28px;margin:12px 0}.card-preview .cost{font-size:21px;color:#ffe07a}.card-preview .warning{color:#ff6573}</style>`);
document.querySelector('header').insertAdjacentHTML('beforeend','<button id="rulesButton" aria-label="Apri le Regole">?</button>');
document.querySelector('header').insertAdjacentHTML('beforeend','<button id="onlineButton" aria-label="Partita online">◎</button>');
document.head.insertAdjacentHTML('beforeend',`<style>
@media(max-width:600px){
 body{font-size:15px;padding-bottom:82px;overflow-x:hidden}header{position:sticky;top:0;z-index:4;padding:8px 10px;gap:6px;background:#070b1df5}.brand{font-size:17px;line-height:1.1}.brand small{font-size:6px}#turnBanner{order:3;margin:0;width:100%;font-size:10px}nav{margin-left:auto;display:grid;grid-template-columns:repeat(4,1fr);gap:3px}nav button,.import{font-size:8px;padding:7px 4px;text-align:center}main{display:flex;flex-direction:column;gap:7px;padding:8px}.player-area{padding:9px}.player-area .core{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin:7px 0;padding:8px}.player-area .core>b,.player-area .stats{grid-column:1/-1}.units{grid-template-columns:repeat(3,1fr);gap:4px}.units strong{margin-top:3px}.units span,.drone{font-size:10px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}#arena{order:-1;min-height:240px}#threeCanvas{height:240px}#centerHud{inset:7px;align-items:flex-start}.briscola{max-width:70%;padding:6px;font-size:10px}.briscola b{font-size:11px}.briscola small{font-size:7px}.moves{padding:6px;font-size:10px}#logPanel{margin:0 8px;height:116px;padding:8px;font-size:12px}#logPanel h2{font-size:10px}#log p{margin:2px 0}footer{padding:0 8px}#hand{min-height:170px;gap:7px;padding:8px 1px 4px;scroll-snap-type:x mandatory;-webkit-overflow-scrolling:touch}.card{flex-basis:132px;min-height:154px;padding:8px;scroll-snap-align:start}.card:hover,.card.selected{transform:translateY(-4px)}.card b{font-size:14px}.card small{font-size:11px}#actions{position:fixed;z-index:5;bottom:0;left:0;right:0;min-height:72px;padding:9px 10px calc(9px + env(safe-area-inset-bottom));background:#080d22f5;border-top:1px solid #345589;gap:6px}#selected{display:none}#endTurn,#aiBtn{min-height:44px;flex:1;font-size:12px}.modal{padding:10px}.modal article{width:100%;padding:20px 14px;font-size:14px}.pool{grid-template-columns:1fr;font-size:12px}
}
@media(min-width:601px) and (max-width:900px){#actions{position:sticky;bottom:0;background:#080d22;padding:10px;z-index:2}.card{flex-basis:150px}}
</style>`);
document.head.insertAdjacentHTML('beforeend',`<style>
#logPanel{display:none}.brand span{color:#ff354c}
@media(max-width:600px){#logButton,#menuButton{display:block;padding:7px 10px;font-size:20px;line-height:1}#logButton{margin-left:auto}#menuButton{margin-left:2px}#hand{padding-top:2px}.card{max-height:142px}}
@media(min-width:601px){#logButton{display:none}}
</style>`);
const C=window.CONFIG,A=new LocalGameAdapter(),savedGame=A.load();C.RULES.DECK_SIZE=40;let s=savedGame||newGame(C),selected=null,needsDeckSetup=!savedGame;s.players.forEach((p,i)=>p.name=`PLAYER ${i+1}`);const $=q=>document.querySelector(q),esc=x=>String(x).replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m])),isPhoneView=()=>matchMedia('(pointer:coarse)').matches&&Math.min(innerWidth,innerHeight)<=600;const R=new TableRenderer($('#threeCanvas'),C);
// La camera e la tavola restano nella stessa vista standard tra un turno e l'altro.
// Il renderer minimale gestisce da sé le posizioni: nessuna luce o animazione aggiuntiva.
document.head.insertAdjacentHTML('beforeend',`<style>@media(max-width:600px){#mobileStatus{height:30svh;padding:3px 8px;gap:4px}.mobile-player{height:100%;max-height:none}.mobile-name{font-size:12px}.mobile-meter{font-size:11px}.mobile-list,.mobile-list span,.mobile-list button{font-size:11px}.mobile-list b{font-size:9px}#hand{align-items:flex-start!important;padding:2px 0!important}.card{height:66%;min-height:0!important;max-height:66%!important}.card b{font-size:17px}.card small{font-size:12px}.mobile-list button{min-height:36px;display:flex;align-items:center}.mobile-list .info-row{min-height:36px;display:flex;align-items:center;width:100%}#centerHud .briscola{padding:7px;max-width:70%}#centerHud .briscola b{font-size:11px;white-space:nowrap}#turnBanner{white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-size:11px}}</style>`);
// Scala reale dell'interfaccia: include anche testi con dimensioni CSS espresse in pixel.
const deckLabel={SCUDO:'Scudi',VIRUS:'Virus',DRONE:'Droni',RADIAZIONE:'Radiazioni',LASER:'Laser',MAGICATA:'Magicate'};
function deckRows(player){return DECK_CATEGORIES.map(category=>`<label>${deckLabel[category]} <small>(${DECK_LIMITS[category]} disponibili)</small><input data-deck-player="${player}" data-deck-category="${category}" type="number" min="0" max="${DECK_LIMITS[category]}" ${category==='MAGICATA'?'readonly':''} value="${DEFAULT_DECK_COUNTS[category]}"></label>`).join('')}
function openDeckBuilder(){modal('deck-builder',`<div class="deck-builder"><h2>COMPOSIZIONE MAZZI — 40 CARTE</h2><p>Ogni giocatore ha un pool indipendente di 67 carte. Scegli <b>38</b> carte tra le cinque categorie; le <b>2 Magicate</b> sono fisse.</p><div class="deck-build-columns"><section><h3>PLAYER 1</h3>${deckRows(0)}</section><section><h3>PLAYER 2</h3>${deckRows(1)}</section></div><p id="deckBuildError"></p><button id="confirmDeckBuild" class="primary">CONFERMA E GENERA I MAZZI</button></div>`);const totals=()=>[0,1].map(player=>DECK_CATEGORIES.filter(c=>c!=='MAGICATA').reduce((sum,c)=>sum+Number(document.querySelector(`[data-deck-player="${player}"][data-deck-category="${c}"]`).value||0),0));const refresh=()=>{const [one,two]=totals(),error=$('#deckBuildError');error.textContent=`Player 1: ${one}/38 · Player 2: ${two}/38`;error.className=one===38&&two===38?'ready':'warning'};document.querySelectorAll('[data-deck-player]').forEach(input=>input.oninput=refresh);refresh();$('#confirmDeckBuild').onclick=()=>{const totalsNow=totals();if(totalsNow.some(total=>total!==38)){alert('Ogni giocatore deve distribuire esattamente 38 carte, più 2 Magicate.');return}const choices=[0,1].map(player=>Object.fromEntries(DECK_CATEGORIES.map(category=>[category,Number(document.querySelector(`[data-deck-player="${player}"][data-deck-category="${category}"]`).value)])));s=newGame(C,Date.now(),choices);needsDeckSetup=false;selected=null;$('#modalRoot').innerHTML='';render()}}
setTimeout(()=>{$('#resetBtn').onclick=()=>{if(confirm('Generare una nuova partita e scegliere entrambi i mazzi?')){A.clear();s=newGame(C);needsDeckSetup=true;selected=null;render();openDeckBuilder()}}},0);
document.head.insertAdjacentHTML('beforeend',`<style>.deck-builder{max-width:860px}.deck-build-columns{display:grid;grid-template-columns:1fr 1fr;gap:18px}.deck-build-columns section{padding:12px;background:#0b1733;border:1px solid #375783}.deck-build-columns h3{margin-top:0}.deck-build-columns label{display:grid;grid-template-columns:1fr auto;gap:8px;align-items:center;margin:7px 0}.deck-build-columns input{width:62px;padding:7px;background:#071126;color:#fff;border:1px solid #5781c6;font:inherit}.deck-builder .warning{color:#ff6573}.deck-builder .ready{color:#61f2a0}@media(max-width:600px){.deck-build-columns{grid-template-columns:1fr}.deck-builder h2{font-size:20px}.deck-builder p,.deck-build-columns label{font-size:14px}}</style>`);
let onlineSession;try{onlineSession=JSON.parse(localStorage.getItem('briscola-multiplayer-session')||'null')}catch{onlineSession=null}
async function onlineRequest(path,options={}){const response=await fetch(`/api/games/${onlineSession.code}${path}`,{...options,headers:{'content-type':'application/json',authorization:`Bearer ${onlineSession.accessToken}`,...options.headers}});const data=await response.json();if(!response.ok)throw Error(data.error||'Errore di rete');return data}
function onlineMode(){return!!onlineSession}
function applyOnline(data){s=data.state;s.players.forEach((p,i)=>p.name=`PLAYER ${i+1}`);render();$('#aiBtn').style.display='none';$('#onlineButton').textContent='◉'}
async function syncOnline(){if(!onlineSession)return;try{applyOnline(await onlineRequest(''))}catch(error){console.warn(error.message)}}
function openOnlineLobby(){modal('online',`<div class="online-lobby"><h2>PARTITA ONLINE</h2><p>Player 1 crea una stanza e invia il codice a Player 2. Ogni azione verrà validata dal server.</p><button id="createOnline" class="primary">CREA PARTITA</button><hr><label>Codice partita <input id="joinCode" maxlength="6" placeholder="ABC123"></label><button id="joinOnline">ENTRA IN PARTITA</button><p id="onlineError" class="warning"></p></div>`);$('#createOnline').onclick=async()=>{try{const counts=s.deckCounts||[DEFAULT_DECK_COUNTS,DEFAULT_DECK_COUNTS],response=await fetch('/api/games',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({deckCounts:counts})}),data=await response.json();if(!response.ok)throw Error(data.error);onlineSession=data;localStorage.setItem('briscola-multiplayer-session',JSON.stringify(data));await syncOnline();$('#modalRoot').innerHTML='';alert(`Partita creata. Codice da inviare a Player 2: ${data.code}`)}catch(error){$('#onlineError').textContent=error.message}};$('#joinOnline').onclick=async()=>{try{const code=$('#joinCode').value.trim().toUpperCase(),response=await fetch(`/api/games/${code}/join`,{method:'POST'}),data=await response.json();if(!response.ok)throw Error(data.error);onlineSession=data;localStorage.setItem('briscola-multiplayer-session',JSON.stringify(data));await syncOnline();$('#modalRoot').innerHTML=''}catch(error){$('#onlineError').textContent=error.message}}}
document.head.insertAdjacentHTML('beforeend',`<style>#onlineButton{font-size:20px}.online-lobby input{display:block;width:100%;padding:10px;margin:7px 0;background:#071126;color:#fff;border:1px solid #5781c6;font:18px monospace}.online-lobby hr{margin:18px 0;border-color:#375783}.online-lobby .warning{color:#ff6573}@media(pointer:coarse){#onlineButton{display:block!important;order:0;min-width:44px;font-size:25px!important}}</style>`);
document.addEventListener('click',event=>{if(event.target.closest('#onlineButton')){event.stopImmediatePropagation();openOnlineLobby()}},true);
setTimeout(()=>{const localDoAct=doAct,localEndTurn=$('#endTurn').onclick;doAct=async action=>{if(!onlineMode())return localDoAct(action);try{applyOnline(await onlineRequest('/action',{method:'POST',body:JSON.stringify({action})}))}catch(error){alert(error.message)}};$('#endTurn').onclick=async()=>{if(!onlineMode())return localEndTurn();try{applyOnline(await onlineRequest('/end-turn',{method:'POST'}))}catch(error){alert(error.message)}};if(onlineSession){syncOnline();setInterval(syncOnline,5000)}},0);
function openDeckList(){const list=player=>[...player.hand,...player.deck,...player.discard].map(id=>byId(id)).filter(Boolean);const panel=(player,index)=>`<section class="deck-list-player"><h3>PLAYER ${index+1} — ${list(player).length}/40 CARTE</h3>${DECK_CATEGORIES.map(category=>{const cards=list(player).filter(card=>card.category===category);return`<h4>${deckLabel[category]} · ${cards.length}</h4><p>${cards.map(card=>`${card.icon} ${esc(card.name)}`).join(' · ')||'—'}</p>`}).join('')}</section>`;modal('deck',`<div class="deck-list"><h2>MAZZI DELLA PARTITA</h2><p>Le due estrazioni sono indipendenti: le stesse carte possono comparire in entrambi i mazzi.</p><div class="deck-build-columns">${s.players.map(panel).join('')}</div></div>`)}
document.addEventListener('click',e=>{if(e.target.closest('[data-modal="deck"]')){e.stopImmediatePropagation();openDeckList()}},true);
const textScale=Math.max(.75,Math.min(1.5,C.UI_TEXT_SCALE||1));document.body.style.zoom=textScale;
// Con lo zoom, le altezze si compensano: le carte restano sempre dentro al display.
document.head.insertAdjacentHTML('beforeend',`<style>
@media(max-width:600px){
 /* Sul telefono si scala solo il testo: nessun elemento può uscire dal display. */
 body{zoom:${textScale}!important;overflow:hidden}#app{height:${100/textScale}svh!important}#arena,#threeCanvas{height:${23/textScale}svh!important}#logPanel{display:none!important}footer{min-height:0}#hand{overflow-y:hidden}
 .mobile-player{max-height:${18/textScale}svh;overflow-y:auto;overscroll-behavior:contain}.modal{top:${72/textScale}px!important;bottom:${120/textScale}px!important;padding:max(12px,env(safe-area-inset-top)) max(12px,env(safe-area-inset-right)) max(12px,env(safe-area-inset-bottom)) max(12px,env(safe-area-inset-left))}.modal article{max-height:calc(${100/textScale}svh - ${216/textScale}px - env(safe-area-inset-top) - env(safe-area-inset-bottom));padding-bottom:26px}.modal article .close{position:sticky;display:block;float:none;margin-left:auto;top:0;z-index:3}.modal-close-bottom{display:block;width:100%;margin-top:18px}
}
</style>`);
document.querySelector('header').insertAdjacentHTML('beforeend','<button id="logButton" aria-label="Apri il Registro di Battaglia">▣</button><button id="menuButton" aria-label="Apri il menu">☰</button>');document.querySelector('header').insertAdjacentHTML('afterend','<div id="briscolaBanner"><span></span><b></b></div>');document.querySelector('#arena').insertAdjacentHTML('beforeend','<div id="arenaControls" aria-label="Zoom arena"><button data-arena="zoomIn" aria-label="Ingrandisci arena">＋</button><button data-arena="zoomOut" aria-label="Riduci arena">−</button></div>');document.querySelector('#arena').insertAdjacentHTML('afterend','<section id="mobileStatus" aria-label="Stato dei giocatori"></section>');
// Geometria mobile deterministica: nessuna altezza percentuale dipende da spazi vuoti.
document.head.insertAdjacentHTML('beforeend',`<style>@media(max-width:600px){.brand small{display:none}header{padding-bottom:26px!important}#turnBanner{position:absolute;left:16px;bottom:3px;order:initial;width:auto;margin:0;font-size:11px}#briscolaBanner{height:${30/textScale}px;display:flex;align-items:center;justify-content:space-between;padding:0 12px;margin-top:3px;border-bottom:1px solid #264277;color:#f5c65c;font:11px monospace}#briscolaBanner b{color:#8bd8ff;font-weight:normal}main{padding-top:3px!important}#mobileStatus{height:${18/textScale}svh!important;flex:none!important}.vs{align-self:stretch!important;display:flex!important;align-items:center!important;justify-content:center!important}footer{flex:0 0 auto!important}#hand{flex:none!important;height:${210/textScale}px!important;min-height:${210/textScale}px!important;align-items:stretch!important}.card{height:100%!important;min-height:0!important;max-height:none!important;overflow:hidden}.card b{font-size:16px!important;line-height:1.04}.card small{font-size:11px!important;line-height:1.08}#centerHud{inset:5px 10px auto;display:flex;justify-content:space-between}.core-hud{font:8px monospace;padding:1px 2px;background:transparent;border:0!important}.core-hud.p1{color:#bfefff}.core-hud.p2{color:#ffd1d7;text-align:right}.core-hud b{display:block;font-size:9px}.core-hud i{display:block;font-style:normal;margin-top:1px}.core-hud em{color:#65f0a5;font-style:normal}.core-hud strong{color:#72dbff}#arena{background:#1b427e}}</style>`);
document.head.insertAdjacentHTML('beforeend',`<style>
.brand span{color:#ff354c}@media(max-width:600px){body{padding-bottom:0;overflow:hidden}#app{height:100dvh;display:flex;flex-direction:column}header{flex:0 0 auto}header nav{display:none;position:absolute;right:8px;top:48px;width:185px;padding:8px;background:#0b1230;border:1px solid #4266a8;grid-template-columns:1fr 1fr;z-index:9}header.menu-open nav{display:grid}#menuButton{display:block;margin-left:auto;padding:7px 10px;font-size:20px;line-height:1}main{display:block;flex:0 0 auto;padding:5px 8px}.player-area{display:none}#arena{height:23dvh;min-height:150px}#threeCanvas{height:23dvh;min-height:150px}#mobileStatus{display:grid;grid-template-columns:1fr 24px 1fr;gap:5px;padding:5px 8px;flex:0 0 auto}.vs{align-self:center;text-align:center;font:bold 11px monospace;color:#f5ca56}.mobile-player{min-width:0;padding:7px;background:#0a1028;border:1px solid #294879}.mobile-player.you{border-color:#37e9ff}.mobile-player.enemy{border-color:#ff354c}.mobile-name{font:bold 10px monospace;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.you .mobile-name{color:#37e9ff}.enemy .mobile-name{color:#ff354c}.mobile-meter{margin-top:4px;font-size:9px}.mobile-meter label{display:flex;justify-content:space-between}.mobile-meter i{display:block;height:4px;background:#172643}.mobile-meter em{display:block;height:100%}.mobile-list{display:grid;gap:2px;margin-top:5px;font-size:9px}.mobile-list b{color:#9ebbe9;font-size:8px}.mobile-list span,.mobile-list button{font-size:9px;padding:2px;background:#142241;border:0;color:#d9e8ff;text-align:left;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}#logPanel{flex:0 0 11dvh;height:11dvh;margin:0 8px;padding:6px;overflow:auto}#summary{font-size:11px}footer{display:flex;flex-direction:column;flex:1;min-height:0;padding:0 8px}#hand{flex:1;min-height:0;height:auto;padding:6px 0;align-items:center}.card{flex-basis:118px;min-height:142px}.card small{font-size:10px}#actions{position:static;flex:0 0 auto;min-height:54px;padding:5px 0 8px;background:transparent;border:0}#endTurn,#aiBtn{min-height:42px}.briscola{max-width:72%;font-size:9px}.briscola span{display:none}.moves{font-size:9px}.modal article{max-height:90dvh}.rules h2{font-size:18px}.rules h3{color:#ffca67;margin:16px 0 4px}.rules p,.rules li{font-size:14px;line-height:1.35}}
@media(min-width:601px){#mobileStatus,#menuButton{display:none}}
</style>`);
function mobileMeter(label,v,max,color){return`<div class="mobile-meter"><label>${label}<b>${v}/${max}</b></label><i><em style="width:${Math.min(100,v/max*100)}%;background:${color}"></em></i></div>`}function mobilePlayer(p,kind,number){return`<div class="mobile-player ${kind}"><div class="mobile-list"><span>◆ DOMINIO ${p.dominance}/${C.RULES.DOMINION_THRESHOLD} · ☢ ${p.radiation}</span><b>SCUDI</b>${p.shields.map((x,i)=>`<button type="button" class="info-row" data-unit="shield" data-owner="${p.id}" data-index="${i}">⬡ ${esc(x.name)} ${x.amount}</button>`).join('')||'<span>—</span>'}<b>VIRUS</b>${p.viruses.map((x,i)=>`<button type="button" class="info-row" data-unit="virus" data-owner="${p.id}" data-index="${i}">⌘ ${esc(x.name)} · ${x.amount}</button>`).join('')||'<span>—</span>'}<b>DRONE</b>${p.drones.map((x,i)=>`<button type="button" data-unit="drone" data-owner="${p.id}" data-index="${i}" class="${x.used?'used':''}">◈ ${esc(x.name)} ${x.attack}/${x.hp}</button>`).join('')||'<span>—</span>'}</div></div>`}
function updateMobileStatus(){$('#mobileStatus').innerHTML=`${mobilePlayer(s.players[0],'you',1)}<div class="vs">VS</div>${mobilePlayer(s.players[1],'enemy',2)}`}
document.head.insertAdjacentHTML('beforeend',`<style>@media(max-width:600px){#mobileStatus{height:${27/textScale}svh!important}#arenaControls{position:absolute;right:7px;bottom:7px;z-index:3;display:grid;grid-template-columns:repeat(2,34px);gap:3px}#arenaControls button{padding:0;height:30px;background:#0b2458e8;border-color:#72aeff;color:#eaf5ff;font-size:16px}}</style>`);
$('#arenaControls').addEventListener('pointerdown',event=>event.stopPropagation());$('#arenaControls').addEventListener('click',event=>{const button=event.target.closest('[data-arena]');if(!button)return;event.stopPropagation();const kind=button.dataset.arena;R.camera.zoom=Math.max(.7,Math.min(2.4,R.camera.zoom+(kind==='zoomIn'?.2:-.2)));R.camera.updateProjectionMatrix()});R.resetView();
document.head.insertAdjacentHTML('beforeend',`<style>@media(max-width:600px){header{padding-bottom:0!important;min-height:${76/textScale}px!important}#turnBanner{top:${48/textScale}px!important;bottom:auto!important;left:16px!important}#briscolaBanner{margin-top:3px!important}main{padding-top:3px!important}#arena{height:${31/textScale}svh!important}#threeCanvas{height:${31/textScale}svh!important}#mobileStatus{height:${22/textScale}svh!important}#hand{height:${25/textScale}svh!important;min-height:${25/textScale}svh!important}.card{height:100%!important}}</style>`);
// Un solo riferimento mobile finale: lo zoom CSS globale rendeva imprevedibile il viewport di Chrome Android.
// Qui le fasce sommano sempre al viewport reale (dvh), senza includere barre del browser.
document.head.insertAdjacentHTML('beforeend',`<style>
@media(max-width:600px){
  *,*::before,*::after{box-sizing:border-box}
  body{zoom:1!important;padding:0!important;overflow:hidden!important}
  #app{height:100dvh!important;min-height:100dvh!important;display:flex!important;flex-direction:column!important;overflow:hidden!important}
  header{flex:0 0 76px!important;min-height:76px!important;padding:8px 10px!important}
  #turnBanner{top:48px!important;bottom:auto!important;left:16px!important}
  #briscolaBanner{flex:0 0 33px!important;height:33px!important;margin:3px 0 0!important}
  main{flex:0 0 55dvh!important;display:block!important;padding:3px 8px!important;overflow:hidden!important}
  #arena,#threeCanvas{height:31dvh!important;min-height:0!important}
  #mobileStatus{height:24dvh!important;display:grid!important;grid-template-columns:1fr 24px 1fr!important;padding:4px 8px!important;gap:5px!important;overflow:hidden!important}
  .mobile-player{height:100%!important;max-height:none!important;overflow:auto!important;overscroll-behavior:contain}
  footer{flex:1 1 auto!important;display:flex!important;flex-direction:column!important;min-height:0!important;padding:0 8px!important;overflow:hidden!important}
  #hand{flex:1 1 auto!important;height:auto!important;min-height:0!important;max-height:none!important;padding:4px 0!important;align-items:stretch!important;overflow-x:auto!important;overflow-y:hidden!important}
  .card{height:100%!important;min-height:0!important;max-height:none!important;flex:0 0 118px!important}
  #actions{position:static!important;flex:0 0 54px!important;min-height:54px!important;padding:5px 0 7px!important}
  #endTurn,#aiBtn{min-height:42px!important}
}
</style>`);
document.head.insertAdjacentHTML('beforeend',`<style>@media(pointer:coarse) and (orientation:landscape) and (max-height:600px){#briscolaBanner{height:30px;display:flex;align-items:center;padding:0 12px;border-bottom:1px solid #264277;color:#f5c65c;font:11px monospace}#briscolaBanner span{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}#briscolaBanner b{margin-left:auto;color:#8bd8ff;font-weight:normal;white-space:nowrap}}</style>`);
// Bersagli tattili ampi: testo invariato, area premibile raddoppiata.
document.head.insertAdjacentHTML('beforeend',`<style>@media(pointer:coarse){#rulesButton,#logButton,#menuButton{order:2;display:block;padding:5px 9px!important;min-width:54px!important;min-height:54px!important;font-size:40px!important;line-height:1!important}#logButton{order:1}#menuButton{order:3}header nav [data-modal="rules"]{display:none!important}header nav button,header nav .import{font-size:16px!important;min-height:44px!important}.mobile-list button,.mobile-list .info-row{min-height:72px!important;padding-top:6px!important;padding-bottom:6px!important;font-size:clamp(12px,4.8vw,18px)!important;line-height:1.15!important;white-space:normal!important;overflow-wrap:anywhere}#centerHud .core-hud{font-size:clamp(10px,3.5vw,16px)!important;min-width:0;overflow-wrap:anywhere}#centerHud .core-hud b{font-size:clamp(12px,4vw,18px)!important}#centerHud .core-hud i{font-size:clamp(10px,3.5vw,16px)!important}.card{container-type:size}.card span{font-size:clamp(8px,7cqh,15px)!important;overflow-wrap:anywhere}.card b{font-size:clamp(12px,12cqh,24px)!important;line-height:1.05;overflow-wrap:anywhere}.card i{font-size:clamp(10px,9cqh,18px)!important}.card small{font-size:clamp(9px,8cqh,16px)!important;line-height:1.08;overflow-wrap:anywhere;overflow:hidden}.card .cost-unavailable{color:#ff354c!important}.unit-detail{color:#dceaff}.unit-detail h2{margin-top:0}.unit-detail .warning{color:#ff6573}.unit-detail .ready{color:#61f2a0}.rules,.rules p,.rules li,#modalLog p{font-size:28px!important;line-height:1.3!important}.rules h2{font-size:36px!important}.rules h3{font-size:31px!important}}@media(pointer:coarse) and (orientation:landscape) and (max-height:600px){#centerHud .core-hud{max-width:30%;line-height:1.2}#centerHud .core-hud.p1{color:#bfefff}#centerHud .core-hud.p2{color:#ffd1d7}#centerHud .core-hud em{color:#65f0a5}#centerHud .core-hud strong{color:#72dbff}#centerHud .core-hud b,#centerHud .core-hud i{display:block}#centerHud .core-hud b{max-width:4.6em}}</style>`);
document.head.insertAdjacentHTML('beforeend','<style>#rulesButton{display:none}@media(pointer:coarse){#rulesButton{display:block!important}header nav{max-height:calc(100dvh - 70px);overflow:auto}header nav button,header nav .import{font-size:16px!important;line-height:1.05!important;min-height:44px!important}.mobile-list>b{font-size:13px!important}.mobile-list>span:first-child{font-size:15px!important}#modalRoot .pool{font-size:24px!important}#modalRoot .pool span{font-size:24px!important;line-height:1.15!important}#hand .card b{font-size:clamp(9px,10.5cqh,21px)!important}}</style>');
document.addEventListener('click',e=>{if(e.target.closest('#rulesButton')){e.stopImmediatePropagation();modal('rules',richRules())}},true);
function openUnitDetail(button){const owner=Number(button.dataset.owner),type=button.dataset.unit,list=type==='shield'?'shields':type==='virus'?'viruses':'drones',item=s.players[owner]?.[list]?.[Number(button.dataset.index)];if(!item)return;const remaining=C.RULES.MOVES_PER_TURN+(s.temp.reducedMoves[s.active]||0)-s.movesUsed;let body='',action='';if(type==='drone'){const usable=owner===s.active&&!item.used&&remaining>0&&!s.winner;body=`<p><b>Drone persistente.</b> Resta sul tavolo e può attaccare una volta per turno.</p><p>Attacco <b>${item.attack}</b> · Integrità <b>${item.hp}</b>.</p>`;action=usable?`<p class="ready">Pronto: usa 1 mossa.</p><button class="primary" data-unit-use="${item.uid}">USA: ATTACCA</button>`:`<p class="warning">${owner!==s.active?'È un Drone dell’avversario.':item.used?'Ha già attaccato in questo turno.':remaining<=0?'Non hai più mosse disponibili.':'La partita è conclusa.'}</p>`}else if(type==='shield'){body=`<p><b>Scudo installato.</b> Assorbe i danni prima che raggiungano il Nucleo.</p><p>Protezione rimasta: <b>${item.amount}</b>.</p><p class="warning">È già attivo: non richiede azioni manuali.</p>`}else{body=`<p><b>Virus installato.</b> Si attiva automaticamente all’inizio del turno del suo proprietario.</p><p>Effetto previsto: <b>${item.amount} danni</b>.</p><p class="warning">È già attivo: non richiede azioni manuali.</p>`}modal('unit',`<div class="unit-detail"><h2>${type==='drone'?'◈':type==='shield'?'⬡':'⌘'} ${esc(item.name)}</h2>${body}${action}</div>`)}
function openCardPreview(cardId){const card=byId(cardId),action={type:'play',cardId,target:1-s.active},reason=legal(s,C,action),usable=!reason;selected=null;modal('card-preview',`<div class="card-preview" style="--c:${card.color}"><span>${card.icon} ${card.category}</span><h2>${esc(card.name)}</h2><p class="cost ${card.cost>s.players[s.active].energy?'warning':''}">${card.cost} ⚡ Energia</p><p>${esc(card.description)}</p>${usable?`<button class="primary" data-play-card="${card.id}">GIOCA</button>`:`<p class="warning">Non giocabile: ${esc(reason)}</p>`}</div>`)}
document.addEventListener('click',e=>{const play=e.target.closest('[data-play-card]');if(play){e.stopImmediatePropagation();const card=byId(play.dataset.playCard),owner=s.active,action={type:'play',cardId:card.id,target:1-s.active};if(!legal(s,C,action)){doAct(action);$('#modalRoot').innerHTML='';if(card.effect==='laser')setTimeout(()=>R.fireLaser(owner),0)}return}const card=e.target.closest('[data-card]');if(card){e.stopImmediatePropagation();openCardPreview(card.dataset.card)}},true);
document.addEventListener('click',e=>{const use=e.target.closest('[data-unit-use]');if(use){e.stopImmediatePropagation();$('#modalRoot').innerHTML='';doAct({type:'attack',uid:use.dataset.unitUse});return}const unit=e.target.closest('[data-unit]');if(unit){e.stopImmediatePropagation();openUnitDetail(unit)}},true);
new MutationObserver(()=>{const p=s.players[s.active];document.querySelectorAll('#hand .card').forEach(card=>{const c=byId(card.dataset.card),cost=card.querySelector('i');if(cost&&c.cost>p.energy)cost.classList.add('cost-unavailable')})}).observe($('#hand'),{childList:true});
setTimeout(()=>{let baseRender=render;render=()=>{baseRender();updateMobileStatus();if(isPhoneView()){$('#turnBanner').textContent=`TURNO ${s.turnId} · PLAYER ${s.active+1}`;$('#briscolaBanner span').textContent=`BRISCOLA ATTIVA · ${s.briscola.name}`;$('#briscolaBanner b').textContent=`MOSSE ${s.movesUsed} / ${C.RULES.MOVES_PER_TURN+(s.temp.reducedMoves[s.active]||0)}`;let p1=s.players[0],p2=s.players[1];$('#centerHud').innerHTML=`<div class="core-hud p1"><b>PLAYER 1</b><i>INTEGRITÀ <em>${p1.integrity}/${C.RULES.CORE_INTEGRITY}</em></i><i>ENERGIA <strong>${p1.energy}/${p1.maxEnergy}</strong></i></div><div class="core-hud p2"><b>PLAYER 2</b><i>INTEGRITÀ <em>${p2.integrity}/${C.RULES.CORE_INTEGRITY}</em></i><i>ENERGIA <strong>${p2.energy}/${p2.maxEnergy}</strong></i></div>`}else{$('#opponent .area-title').textContent='PLAYER 2';$('#current .area-title').textContent='PLAYER 1'}};render()},0);
$('#menuButton').onclick=()=>document.querySelector('header').classList.toggle('menu-open');
$('#logButton').onclick=()=>modal('registro',`<div class="rules"><h2>Registro di Battaglia</h2><p>Qui trovi ogni azione già risolta, utile per riprendere una partita asincrona.</p><div id="modalLog">${s.history.map(x=>`<p><b>Turno ${x.turnId}</b> — ${esc(x.text)}</p>`).join('')}</div></div>`);
// Quando la partita finisce, il pannello esito offre sempre una nuova partita immediata.
new MutationObserver(()=>{let article=document.querySelector('#modalRoot article');if(article&&/VITTORIA|SCONFITTA/.test(article.textContent)&&!article.querySelector('#restartGame'))article.insertAdjacentHTML('beforeend','<button id="restartGame" class="primary">RICOMINCIA PARTITA</button>')}).observe($('#modalRoot'),{childList:true,subtree:true});
document.addEventListener('click',e=>{if(e.target.closest('#restartGame')){s=newGame(C);selected=null;$('#modalRoot').innerHTML='';render()}},true);
new MutationObserver(()=>{let article=document.querySelector('#modalRoot article');if(article&&!article.querySelector('#closeModal'))article.insertAdjacentHTML('beforeend','<button id="closeModal" class="modal-close-bottom">CHIUDI</button>')}).observe($('#modalRoot'),{childList:true,subtree:true});
document.addEventListener('click',e=>{if(e.target.closest('#closeModal'))$('#modalRoot').innerHTML=''},true);
function richRules(){return`<div class="rules"><h2>Regole di BRISCOLA MAGICATA</h2><p><b>Scopo della partita.</b> Vinci in due modi: riduci l’<b>Integrità</b> del Nucleo avversario a zero, oppure inizia ${C.RULES.DOMINION_TURNS_TO_WIN} dei tuoi turni consecutivi con almeno ${C.RULES.DOMINION_THRESHOLD} punti <b>Dominio</b>. Non esiste un timer: la partita può proseguire per giorni.</p><h3>1. Turni, Energia e mosse</h3><p>Nel tuo turno l’Energia torna al massimo attuale e peschi una carta. Puoi eseguire fino a ${C.RULES.MOVES_PER_TURN} mosse: giocare una carta, attivare un effetto o ordinare l’attacco di un Drone. Puoi terminare anche prima con <b>Fine Turno</b>; dopo la conferma il turno non può essere modificato.</p><h3>2. Nucleo, Integrità e Scudi</h3><p>Il <b>Nucleo</b> è la Cittadella Orbitale del giocatore: parte con ${C.RULES.CORE_INTEGRITY} Integrità. Gli <b>Scudi</b> sono protezioni installate davanti al Nucleo: assorbono il danno in ordine, poi l’eventuale danno residuo colpisce il Nucleo. Alcuni Scudi hanno varianti speciali, ma tutti mostrano chiaramente la protezione rimasta.</p><h3>3. Drone</h3><p>I <b>Drone</b> sono unità meccaniche persistenti: restano sul tavolo e hanno Attacco/Integrità, ad esempio 2/3. Clicca un Drone disponibile per ordinargli un attacco al Nucleo nemico: conta come una mossa. Un Drone può attaccare una volta per turno; alcuni producono Dominio o hanno abilità difensive.</p><h3>4. Virus e Radiazione</h3><p>I <b>Virus</b> sono sabotaggi informatici installati sull’avversario. L’avversario vede un’anomalia, e il Virus si attiva automaticamente all’inizio del suo turno: nessuna risposta in tempo reale è richiesta. La <b>Radiazione</b> (☢) è un danno persistente: ogni inizio turno infligge 1 danno e diminuisce di 1, fino a sparire.</p><h3>5. Laser, Briscola e Magicate</h3><p>I <b>Laser</b> infliggono danno immediato e costano Energia. La <b>Briscola</b> è una regola globale estratta periodicamente: vale per entrambi fino alla successiva. Le <b>Magicate</b> sono carte rare e potenti, con effetti insoliti ma sempre registrati nel Registro di Battaglia.</p><h3>6. Registro, Direttive e mazzo</h3><p>Il <b>Registro di Battaglia</b> racconta azioni, danni, scudi, Briscole ed effetti risolti, così puoi riprendere una partita asincrona senza dubbi. Le <b>Direttive</b> sono reazioni automatiche impostate in precedenza. Se il mazzo finisce, ogni pesca mancata causa danno crescente al proprietario.</p></div>`}
document.addEventListener('click',e=>{let b=e.target.closest('[data-modal="rules"]');if(b){e.stopImmediatePropagation();modal('rules',richRules())}},true);
function meter(label,v,max,color){return`<div class="meter"><label>${label} <b>${v}/${max}</b></label><i><em style="width:${Math.min(100,v/max*100)}%;background:${color}"></em></i></div>`}function player(p,enemy){return`<div class="area-title">${enemy?'AVVERSARIO':'TU'} · ${p.name}</div><div class="core"><b>◉ NUCLEO</b>${meter('INTEGRITÀ',p.integrity,C.RULES.CORE_INTEGRITY,C.COLORS.INTEGRITY)}${meter('ENERGIA',p.energy,p.maxEnergy,C.COLORS.ENERGY)}<div class="stats">◆ DOMINIO <b>${p.dominance}/${C.RULES.DOMINION_THRESHOLD}</b> · ☢ ${p.radiation}</div></div><div class="units"><strong>SCUDI</strong> ${p.shields.map(x=>`<span>⬡ ${esc(x.name)} ${x.amount}</span>`).join('')||'—'}<strong>DRONE</strong>${p.drones.map(x=>`<button class="drone ${x.used?'used':''}" data-attack="${x.uid}" title="Attacca: ${x.attack} danni">◈ ${esc(x.name)} ${x.attack}/${x.hp}</button>`).join('')||'—'}<strong>VIRUS</strong>${p.viruses.map(x=>`<span>⌘ Anomalia</span>`).join('')||'—'}</div>`}
function render(){let p=s.players[s.active],o=s.players[1-s.active];$('#opponent').innerHTML=player(o,true);$('#current').innerHTML=player(p,false);$('#turnBanner').textContent=`TURNO ${s.turnId} · ${p.name}`;$('#centerHud').innerHTML=`<div class="briscola"><small>BRISCOLA ATTIVA · ROUND ${s.round}</small><b>${s.briscola.icon} ${esc(s.briscola.name)}</b><span>${esc(s.briscola.description)}</span></div><div class="moves">MOSSE <b>${s.movesUsed} / ${C.RULES.MOVES_PER_TURN+(s.temp.reducedMoves[s.active]||0)}</b></div>`;$('#summary').textContent=s.history[0]?.text||'';$('#log').innerHTML=s.history.slice(0,18).map(x=>`<p class="${x.type}"><small>T${x.turnId}</small> ${esc(x.text)}</p>`).join('');$('#hand').innerHTML=p.hand.map(id=>{let c=byId(id);return`<button class="card ${selected===id?'selected':''}" data-card="${id}" style="--c:${c.color}" title="${esc(c.description)}"><span>${c.icon} ${c.category}</span><b>${esc(c.name)}</b><i>${c.cost} ⚡</i><small>${esc(c.description)}</small></button>`}).join('');$('#selected').textContent=selected?`Carta selezionata: ${byId(selected).name}. Clicca di nuovo per giocarla contro l’avversario.`:'Seleziona una carta per leggere il tooltip e giocarla.';$('#endTurn').disabled=!!s.winner;R.update(s);A.save(s);if(s.winner!==null)modal('fine',`<h2>${s.winner===s.active?'VITTORIA':'SCONFITTA'}</h2><p>${s.players[s.winner].name} controlla il settore orbitale.</p>`)}
function doAct(a){try{s=act(s,C,a);selected=null;render()}catch(e){alert(e.message)}}document.addEventListener('click',e=>{let c=e.target.closest('[data-card]');if(c){let id=c.dataset.card;if(selected===id)doAct({type:'play',cardId:id,target:1-s.active});else{selected=id;render()}return}let d=e.target.closest('[data-attack]');if(d)doAct({type:'attack',uid:d.dataset.attack});let m=e.target.dataset.modal;if(m)showModal(m)});$('#endTurn').onclick=()=>{let remaining=C.RULES.MOVES_PER_TURN+(s.temp.reducedMoves[s.active]||0)-s.movesUsed;if(remaining>0&&!confirm(`Restano ${remaining} mosse. Confermi Fine Turno?`))return;s=endTurn(s,C);render()};$('#aiBtn').onclick=()=>{for(let i=0;i<C.RULES.MOVES_PER_TURN;i++)s=autoPlay(s,C);s=endTurn(s,C);render()};$('#saveBtn').onclick=()=>{A.save(s);alert('Salvataggio locale aggiornato.')};$('#resetBtn').onclick=()=>{if(confirm('Eliminare il salvataggio locale e iniziare una nuova partita?')){A.clear();s=newGame(C);render()}};$('#exportBtn').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([A.export(s)],{type:'application/json'}));a.download='neon-war-save.json';a.click();URL.revokeObjectURL(a.href)};$('#importInput').onchange=async e=>{try{s=A.import(await e.target.files[0].text());render()}catch(x){alert('Importazione non valida: '+x.message)}};
function modal(kind,content){$('#modalRoot').innerHTML=`<div class="modal"><article><button class="close">×</button>${content}</article></div>`;$('.close').onclick=()=>$('#modalRoot').innerHTML=''}function showModal(k){if(k==='rules')modal(k,`<h2>REGOLE</h2><p>Riduci l’Integrità avversaria a zero o mantieni ${C.RULES.DOMINION_THRESHOLD} Dominio per ${C.RULES.DOMINION_TURNS_TO_WIN} turni propri. Ogni turno hai ${C.RULES.MOVES_PER_TURN} mosse e l’Energia si ripristina. Scudi assorbono danni; Drone attaccano; Virus e Radiazione colpiscono nel turno futuro; la Briscola cambia le regole globali.</p><h3>Direttive</h3><p>Sono reazioni automatiche già impostate: non richiedono che l’avversario sia connesso.</p>`);if(k==='tutorial')modal(k,`<h2>TUTORIAL RAPIDO</h2><ol><li>Scegli una carta dalla mano; cliccala di nuovo per usarla.</li><li>Usa Drone persistenti cliccandoli.</li><li>Controlla Energia e MOSSE, poi premi Fine Turno.</li><li>Leggi il Registro al centro per ricostruire una partita asincrona.</li></ol>`);if(k==='deck')modal(k,`<h2>DECK BUILDING</h2><p>Mazzi pronti: Bastione Orbitale e Piaga Rossa (30 carte, massimo ${C.RULES.MAX_MAGIFICATE} Magicate). Il pool contiene ${CARD_POOL.length} carte; in questa versione i mazzi pronti sono bilanciati e modificabili in <code>src/data/cards.js</code>.</p><button id="bast">USA BASTIONE</button> <button id="piaga">USA PIAGA ROSSA</button><div class="pool">${CARD_POOL.map(c=>`<span>${c.icon} ${esc(c.name)} (${c.cost})</span>`).join('')}</div>`);setTimeout(()=>{let b=$('#bast'),p=$('#piaga');if(b)b.onclick=()=>{s=newGame(C);s.players[0].deck=preset('BASTIONE ORBITALE');render();$('#modalRoot').innerHTML=''};if(p)p.onclick=()=>{s=newGame(C);s.players[0].deck=preset('PIAGA ROSSA');render();$('#modalRoot').innerHTML=''}},0)}render();
